swagger:
  # 是否启用swagger聚合服务
  enable: true
spring:
  application:
    # 聚合网关处服务中英文对照
    names: user-server:用户服务,common-server:基础服务
gateway:
  check:
    # 是否校验token
    token: false
    ignoreToken:
      path: /common-server/auth/login, /common-server/auth/refresh, /common-server/auth/check, /common-server/auth/info
    staticResource:
      path: /**/favicon.ico, /**/v2/api-docs, /**/doc.html, /**/swagger-ui.html, /**/swagger-resources, /**/webjars/**