server:
  port: 7777

spring:
  active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 1846c7d2-6bba-4b98-8538-0f7b291d6b41
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 1846c7d2-6bba-4b98-8538-0f7b291d6b41
