server:
  port: 9999

spring:
  application:
    name: analysis-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 1846c7d2-6bba-4b98-8538-0f7b291d6b41
  kafka:
    bootstrap-servers: 192.168.31.5:9092, 192.168.31.5:9093
#    producer:
#      batch-size: 5
#      buffer-memory: 33554432
#    consumer:
#      max-poll-records: 1
#      auto-offset-reset: latest
