server:
  port: 8000


spring:
  application:
    name: plarform-admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 1846c7d2-6bba-4b98-8538-0f7b291d6b41

